frontend/app/.server/locales/estimator-en.json, frontend/app/.server/locales/estimator-fr.json, frontend/app/.server/locales/index.ts
Adding initial files for the estimator locales.
=> Add estimator locale files

frontend/app/components/app-bar.tsx, frontend/app/components/language-switcher.tsx, frontend/app/routes/layout.tsx, frontend/tests/components/__snapshots__/app-bar.test.tsx.snap, frontend/tests/components/__snapshots__/language-switcher.test.tsx.snap
Move language switcher in layout header
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> Move language switcher in layout header

frontend/app/.server/locales/public-en.json, frontend/app/.server/locales/public-fr.json, frontend/app/components/page-title.tsx, frontend/app/routes/estimator/results.tsx, frontend/app/routes/estimator/step-age.tsx, frontend/app/routes/estimator/step-disability-tax-credit.tsx, frontend/app/routes/estimator/step-incarceration.tsx, frontend/app/routes/estimator/step-income-tax-return.tsx, frontend/app/routes/estimator/step-income.tsx, frontend/app/routes/estimator/step-marital-status.tsx, frontend/app/routes/estimator/step-residency.tsx, frontend/app/routes/estimator/step-status-in-canada.tsx
Add subTitle option to PageTitle component
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
Provide screenshots or screen-recordings …
=> feature(frontend): Add subTitle option to PageTitle component

frontend/app/components/collapsible.tsx, frontend/app/routes/index.tsx
=> Add collapsible component

frontend/app/components/collapsible.tsx
- [ ✔ ] ✨ **new feature** -- non-breaking change that adds functionality
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR …
=> change collapsible component style

frontend/tests/components/__snapshots__/page-title.test.tsx.snap, frontend/tests/components/page-title.test.tsx
Add tests to cover page-title subTitle option
=> test(frontend): Add tests to cover page-title subTitle option

frontend/app/.server/locales/public-en.json, frontend/app/.server/locales/public-fr.json, frontend/app/components/age-picker-field.tsx, frontend/app/routes/index.tsx, frontend/app/utils/age-utils.ts, package-lock.json
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> add age display to the age-picker

.github/workflows/build-frontend.yaml
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> build(frontend): add typecheck to action

frontend/app/utils/age-utils.ts, frontend/tests/utils/age-utils.test.ts
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> refactor(frontend): Improve on age-utils and add tests

frontend/app/.server/express/middleware.ts
Add 'data:' in img-src CSP configurations. It was accidentally removed when including Adobe Analytics configuration.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include diagrams, screenshots, or …
=> fix(frontend) Add 'data:' in img-src CSP configurations

frontend/app/utils/date-utils.ts, frontend/tests/utils/date-utils.test.ts
Update dateExists to specify month 1-12 and support year < 100
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
Provide screenshots …
=> refactor(frontend): Update dateExists to specify month 1-12

frontend/app/utils/age-utils.ts, frontend/tests/utils/age-utils.test.ts
Fix age utils calculations and tests
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> fix(frontend) Fix age utils calculations and tests

frontend/app/routes/index.tsx
Remove clamp on dashboard content width
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> fix(frontend) Remove clamp on dashboard content width

frontend/app/routes/layout.tsx
Abbreviate language toggle on md screen
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> fix(frontend) Abbreviate language toggle on md screen

frontend/app/.server/locales/estimator-en.json, frontend/app/.server/locales/estimator-fr.json, frontend/app/hooks/use-error-translation.ts, frontend/app/routes/estimator/@types.d.ts, frontend/app/routes/estimator/results.tsx, frontend/app/routes/estimator/step-age.tsx, frontend/app/routes/estimator/step-income.tsx, frontend/app/routes/estimator/step-marital-status.tsx
Implement step 3 : income (missing additional info hints). includes an overhaul of the form schema for step 1, 2 and 3.
adds useErrorTranslation hook that allows the schema to specify errors using a partial i18n localization key suffix (like "field-name.error.invalid") while the hook is initialized with the namespace and i18n key prefix. this allows more flexibility than directly translating the error messages in the schema
minor changes to main schema
<details>
<summary>Linting and …
=> Income step

frontend/app/.server/locales/estimator-en.json, frontend/app/.server/locales/estimator-fr.json, frontend/app/routes/estimator/step-age.tsx, frontend/app/routes/estimator/step-income.tsx, frontend/app/routes/estimator/step-marital-status.tsx
adds income step field details (help/info messages)
refactors field error localizations
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> adds income field details

frontend/app/components/error-summary.tsx, frontend/app/components/language-switcher.tsx
Auto-sync i18n language with current route language and configure language switcher `reloadDocument:false`
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include diagrams, screenshots, or alternative …
=> feat(frontend): auto-sync i18n language with current route language

frontend/app/.server/locales/estimator-en.json, frontend/app/.server/locales/estimator-fr.json, frontend/app/routes/estimator/@types.d.ts, frontend/app/routes/estimator/results.tsx
* Feed all the input data into the "What you told us" section
* Show the proper result text block based on marital status
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> Add all form data to the What you told us section

frontend/app/components/language-switcher.tsx
Add namespace to useTranslation to prevent 404 fetching of `/api/translations?ns=translation&lng=fr&v=00000000`
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include diagrams, screenshots, or alternative …
=> fix(frontend) Add namespace to useTranslation to prevent 404

frontend/app/components/age-picker-field.tsx
Set year value to undefined when NaN. I may change back values to string in the future.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> fix(frontend) Set year value to undefined when NaN

frontend/app/routes/estimator/calculator.ts, frontend/app/routes/estimator/results.tsx
Add the estimate calculator and show results on the result page
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> add estimates calculator WIP

frontend/app/.server/utils/route-utils.ts, frontend/app/entry.server.tsx, frontend/app/hooks/use-language.ts, frontend/app/i18n-config.server.ts, frontend/app/utils/i18n-utils.ts, frontend/tests/utils/i18n-utils.test.ts
Rename getLanguage to getLanguageFromResource since it's determine by the route and not the i18n provider
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include diagrams, screenshots, or alternative …
=> refactor(frontend) Rename getLanguage to getLanguageFromResource

frontend/app/utils/state-utils.ts, frontend/tests/utils/state-utils.test.ts
[5476](https://dev.azure.com/DTS-STN/Canada%20Disability%20Benefit/_workitems/edit/5476)
adds tests for state-utils and some refactoring/bug fixes for the getStateRoute function
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> add tests for estimatorStepGate function

frontend/app/routes/estimator/results.tsx
Move 'what you told us' section out of main component
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> Move 'what you told us' section out of main component

frontend/app/routes/estimator/@types.d.ts, frontend/app/routes/estimator/results.tsx
refactor results page: move results schema to loader, add the 2 calculated results to the schema.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> move formatted results schema to loader

frontend/app/routes/estimator/@types.d.ts, frontend/app/routes/estimator/calculator.ts, frontend/app/routes/estimator/results.tsx
refactor calculator code and fix some values that could go out of range 
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> refactor results calculation

frontend/app/.server/environment/adobe-analytics.ts, frontend/app/components/breadcrumbs.tsx, frontend/app/root.tsx, frontend/app/routes/estimator/results.tsx, frontend/app/routes/estimator/step-income.tsx, frontend/app/routes/estimator/step-marital-status.tsx, frontend/app/routes/index.tsx, frontend/app/routes/layout.tsx, frontend/app/utils/adobe-analytics-utils.ts
[5478](https://dev.azure.com/DTS-STN/Canada%20Disability%20Benefit/_workitems/edit/5478)
add Adobe Analytics custom clicks to buttons and links
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include …
=> add Adobe Analytics custom clicks to buttons and links

frontend/app/routes/estimator/step-income.tsx, frontend/app/routes/estimator/step-marital-status.tsx
Set previous/next button size `size="lg"`
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
Provide screenshots or screen-recordings …
=> design(frontend) Set previous/next button size to lg

frontend/app/routes/layout.tsx
Change language switcher abbreviation display breakpoint
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> design(frontend) Change language switcher abbreviation display breakpoint

frontend/app/.server/locales/estimator-en.json, frontend/app/.server/locales/estimator-fr.json
fixes text casing for field errors, clean up french localization text
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> fix inconsistent text casing for field errors

frontend/app/.server/locales/estimator-en.json, frontend/app/.server/locales/estimator-fr.json, frontend/app/routes/estimator/results.tsx
Apply EN content changes to results page
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> Apply EN content changes to results page

frontend/app/.server/environment/client.ts, frontend/app/.server/environment/estimator.ts, frontend/app/.server/environment/server.ts, frontend/app/routes/estimator/calculator.ts
make the calculator constants configurable (providing sane defaults)
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> adds calculator constants to configuration

frontend/app/routes/estimator/step-income.tsx, frontend/app/utils/date-utils.ts
calculate the year for the "last year's income tax return"
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> obtain the previous income tax return year dynamicaly

frontend/app/.server/locales/common-en.json, frontend/app/.server/locales/common-fr.json, frontend/app/.server/locales/estimator-en.json, frontend/app/.server/locales/estimator-fr.json, frontend/app/routes/estimator/results.tsx, frontend/app/routes/estimator/step-income.tsx, frontend/app/routes/estimator/step-marital-status.tsx, frontend/app/routes/index.tsx
cleanup localization
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> cleanup localizations

frontend/app/.server/environment/estimator.ts, frontend/app/routes/estimator/layout.tsx, frontend/app/routes/index.tsx
fix breadcrumb i18n namespace issue
fix inline link hydration issue
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
returning URL from the config causes the hydration issue, returning a string instead
=> fixes hydration issue, fixes index breadcrumb label key

frontend/app/.server/locales/estimator-en.json
update error text for UCCB and RDSP fields
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> fix UCCB and RDSP error messages

frontend/app/routes/estimator/step-income.tsx
turn off form field autocomplete for income step fields
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> style(frontend): increase Radio size

frontend/app/.server/locales/estimator-en.json, frontend/app/.server/locales/estimator-fr.json, frontend/app/routes/estimator/results.tsx, frontend/app/routes/estimator/step-income.tsx
minor text updates
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
Provide screenshots or screen-recordings to help reviewers …
=> add missing result text, change estimate button text

frontend/app/.server/express/server.ts, frontend/app/.server/logging.ts
Whenever a new logger is created by winston, it adds two new event listeners (one for `uncaughtException` and one for `unhandledRejection`).
Nodejs configures `process.maxListeners` to be 10 by default, and then issues the following warning if more than the max are registered:
```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. XX event listeners added to [process]. MaxListeners is YY. Use emitter.setMaxListeners() to increase limit.
```
This PR simply increments `process.maxListeners` by two every time a new logger is created to accommodate the new listeners added by winston.
Before submitting this PR, ensure that you have completed the following. You …
=> fix(frontend): tweak setMaxListeners() call

gitops/base/cdb-estimator-frontend/deployments.yaml
Reduce configure request/limits
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
Provide screenshots or screen-recordings to help …
=> build(gitops) Reduce configure request/limits

frontend/app/.server/locales/common-fr.json, frontend/app/.server/locales/estimator-en.json, frontend/app/.server/locales/estimator-fr.json
localization updated, mainly updates to FR content
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> localization updates

frontend/app/.server/utils/security-utils.ts
This PR modifies the Redacted class to output undefined when calling toString() to help improve environment variable logging.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include diagrams, screenshots, …
=> fix(frontend): update Redacted class to return undefined when no initial value is provided

frontend/app/@types/global.d.ts, frontend/app/@types/i18next.d.ts, frontend/app/components/breadcrumbs.tsx, frontend/app/components/error-boundaries.tsx, frontend/app/i18n-config.server.ts, frontend/app/root.tsx, frontend/app/routes/layout.tsx, frontend/app/utils/i18n-utils.ts, frontend/tests/components/links.test.tsx, frontend/tests/utils/i18n-utils.test.ts
Tighten Language type with module augmentation.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> refactor(frontend) tighten Language type

frontend/app/.server/locales/estimator-en.json
English v3 content update
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> English v3 content update

frontend/app/routes/estimator/step-income.tsx
fixes invalid markup in income step
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> fix invalid markup

frontend/app/.server/locales/estimator-en.json, frontend/app/.server/locales/estimator-fr.json, frontend/app/routes/estimator/@types.d.ts, frontend/app/routes/estimator/results.tsx, frontend/app/routes/index.tsx
* change "Total income" to "Your total income" to make it clearer
* removed CDB link from landing page intro
* open "next step" links in new window
* fix capitalization on the Estimate button
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> Misc tweaks

frontend/app/routes/estimator/results.tsx, frontend/app/utils/cdb-calculator.ts, frontend/tests/utils/cdb-calculator-test.ts
Add calculator test file, update total income calculation
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> Add calculator test file, update total income calculation

frontend/app/components/adobe-analytics-script.tsx, frontend/app/hooks/use-push-pageview-event.ts, frontend/app/root.tsx, frontend/tests/components/__snapshots__/adobe-analytics-script.test.tsx.snap, frontend/tests/components/adobe-analytics-script.test.tsx, frontend/tests/hooks/use-push-pageview-event.test.ts, frontend/tests/utils/adobe-analytics-utils.test.ts
refactor adobe analytics as react components and hook
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> refactors adobe analytics and adds tests

frontend/app/components/error-summary.tsx, frontend/app/routes/estimator/step-income.tsx, frontend/app/routes/estimator/step-marital-status.tsx
Scrolling only on error updates.
- Fixes scrolling on language change
- Fixes smooth scrolling issue when used in useEffect
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include diagrams, screenshots, or …
=> fix(frontend) Scrolling on error updates

frontend/app/components/CurrencyField.tsx, frontend/app/components/adobe-analytics-script.tsx, frontend/app/components/error-summary.tsx, frontend/app/components/input-field.tsx, frontend/app/hooks/use-push-pageview-event.ts, frontend/app/root.tsx, frontend/app/routes/estimator/step-income.tsx, frontend/app/routes/estimator/step-marital-status.tsx, frontend/app/utils/string-utils.ts, frontend/package-lock.json, frontend/tests/components/__snapshots__/adobe-analytics-script.test.tsx.snap, frontend/tests/components/adobe-analytics-script.test.tsx, frontend/tests/components/currency-field.test.tsx, frontend/tests/hooks/use-push-pageview-event.test.ts, frontend/tests/utils/adobe-analytics-utils.test.ts, frontend/tests/utils/string-utils.test.ts
adds currency field component
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> adds number formatting for currency fields

gitops/overlays/staging/configs/cdb-estimator-frontend/config.conf, gitops/overlays/staging/external-secrets.yaml, gitops/overlays/staging/ingresses.yaml, gitops/overlays/staging/kustomization.yaml, gitops/overlays/staging/patches/deployments.yaml
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> Adding staging environment for HLA

frontend/tests/components/__snapshots__/breadcrumbs.test.tsx.snap, frontend/tests/components/breadcrumbs.test.tsx
adds breadcrumb tests
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> adds tests for breadcrumbs component

frontend/app/.server/environment/adobe-analytics.ts
Update default Adobe Analytics script to use Authenticated
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> Update default Adobe Analytics script to use Authenticated

frontend/app/.server/locales/common-en.json, frontend/app/.server/locales/common-fr.json, frontend/app/i18n-config.server.ts, frontend/app/root.tsx, frontend/app/routes/estimator/results.tsx, frontend/app/routes/estimator/step-income.tsx, frontend/app/routes/estimator/step-marital-status.tsx, frontend/app/routes/index.tsx, frontend/app/routes/splash.tsx, frontend/app/utils/meta-utils.ts, frontend/app/utils/seo-utils.ts, frontend/app/utils/string-utils.ts
Add dcterms and other metadata information
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
Provide screenshots or screen-recordings …
=> fix(frontend) Add dcterms and other meta information

frontend/app/.server/environment/estimator.ts, frontend/app/.server/locales/estimator-en.json, frontend/app/.server/locales/estimator-fr.json, frontend/app/routes/estimator/results.tsx, frontend/app/routes/index.tsx
make contact link configuration-driven
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> make contact link configuration-driven

gitops/overlays/dev/ingresses.yaml, gitops/overlays/staging/ingresses.yaml
Ensure SSL redirect is on for nginx.
`nginx.ingress.kubernetes.io/ssl-redirect: "true"`
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> fix(gitops): Ensure SSL redirect is on for nginx

frontend/.env.example
Add configurations to .env.example
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> add configurations to .env.example

frontend/tests/components/__snapshots__/footer.test.tsx.snap, frontend/tests/components/footer.test.tsx
add footer test
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> adds footer test

frontend/app/components/contextual-alert.tsx, frontend/tests/components/__snapshots__/contextual-alert.test.tsx.snap, frontend/tests/components/contextual-alert.test.tsx
adds contextual alert tests
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> adds contextual alert tests

frontend/package-lock.json, frontend/package.json
Remove unused dependencies for cleanup
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> chore(frontend) Remove unused dependencies for cleanup

LICENSE.md, README.md, frontend/.vscode/extensions.json, frontend/LICENSE.md, gitops/LICENSE.md
Cleanup documentation
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
Provide screenshots or screen-recordings to help reviewers …
=> Cleanup documentation

frontend/app/.server/environment/estimator.ts, frontend/app/.server/locales/estimator-en.json, frontend/app/.server/locales/estimator-fr.json, frontend/app/routes/estimator/step-income.tsx
remove the working income vs net income check
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> remove working income vs net income validation

frontend/playwright.config.ts
Add global timeout settings for Playwright
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> add playwright global timeouts

frontend/app/routes/estimator/results.tsx
Add counter on estimator results `estimator.success.total`
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> metric(frontend) Add counter on estimator results

frontend/app/routes/estimator/results.tsx
show single-divorced estimate text when the married estimate and split benefit is the same amount
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include diagrams, screenshots, or alternative approaches …
=> married estimate display tweak

frontend/app/components/footer.tsx, frontend/tests/components/__snapshots__/footer.test.tsx.snap
Fix skip navigation to footer
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
Provide screenshots or screen-recordings to help …
=> fix(fronted) Fix skip navigation to footer

frontend/app/.server/locales/estimator-en.json, frontend/app/.server/locales/estimator-fr.json, frontend/app/components/currency-field.tsx, frontend/app/routes/estimator/step-income.tsx, frontend/e2e/__snapshots__/estimator/step-income.spec.ts/Navigating-to-en-income-renders-the-english-income-page-1.txt, frontend/e2e/__snapshots__/estimator/step-income.spec.ts/Navigating-to-fr-revenus-renders-the-french-income-page-1.txt
Applies income step text changes stemming for them UAT feedback 
- [] added or updated tests to verify the changes
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> applies text chanages to income page

frontend/app/.server/locales/estimator-en.json, frontend/app/.server/locales/estimator-fr.json, frontend/app/routes/estimator/results.tsx, frontend/e2e/__snapshots__/estimator/results.spec.ts/Navigating-to-en-results-renders-the-english-results-page-1.txt, frontend/e2e/__snapshots__/estimator/results.spec.ts/Navigating-to-fr-resultats-renders-the-french-results-page-1.txt
Implement misc. changes (requests following UAT) to the Results page.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> Results uat changes

frontend/app/.server/locales/estimator-en.json, frontend/app/.server/locales/estimator-fr.json, frontend/app/routes/index.tsx, frontend/e2e/__snapshots__/index.spec.ts/Navigating-to-en-renders-the-english-dashboard-page-1.txt, frontend/e2e/__snapshots__/index.spec.ts/Navigating-to-fr-renders-the-french-dashboard-page-1.txt
Implement text change request issued by UAT.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> Eligibility text changes

frontend/app/.server/locales/estimator-fr.json, frontend/e2e/__snapshots__/estimator/step-marital-status.spec.ts/Navigating-to-fr-etat-civil-renders-the-french-marital-status-page-1.txt, frontend/e2e/__snapshots__/index.spec.ts/Navigating-to-fr-renders-the-french-dashboard-page-1.txt
Latest french text update for index page and marital-status page.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> Fr uat update index marital

frontend/app/.server/locales/estimator-fr.json, frontend/e2e/__snapshots__/estimator/step-income.spec.ts/Navigating-to-fr-revenus-renders-the-french-income-page-1.txt, frontend/e2e/__snapshots__/index.spec.ts/Navigating-to-fr-renders-the-french-dashboard-page-1.txt
Implement latest FR updates (UAT)
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> implement latest FR changes

gitops/overlays/staging/patches/deployments.yaml
- [a] ⚙️ **build or tooling** -- ex: CI/CD, dependency upgrades
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces …
=> (gitops) Pin staging version

frontend/app/.server/locales/estimator-fr.json
French localization : replace "conjoint" with "partenaire"
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> replace conjoint with partenaire

frontend/e2e/estimator/results.spec.ts, frontend/e2e/estimator/step-income.spec.ts, frontend/e2e/estimator/step-marital-status.spec.ts, frontend/e2e/index.spec.ts, frontend/e2e/models/PlaywrightBasePage.ts, frontend/e2e/models/PlaywrightEstimatorPage.ts, frontend/e2e/not-found.spec.ts, frontend/e2e/single-results.spec.ts, frontend/e2e/splash.spec.ts, frontend/e2e/steps-navigation.spec.ts, frontend/playwright.config.ts
Improve some E2E tests.  Setup basic Page Object Model structure with isLoaded verifications
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> e2e(frontend) Improve some E2E tests

gitops/overlays/staging/patches/deployments.yaml
SNAPSHOT-00141-ac950466
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> staging SNAPSHOT-00141-ac950466

frontend/app/.server/locales/common-en.json, frontend/app/.server/locales/common-fr.json, frontend/app/.server/locales/estimator-en.json, frontend/app/.server/locales/estimator-fr.json, frontend/app/routes/estimator/step-income.tsx, frontend/app/routes/estimator/step-marital-status.tsx, frontend/e2e/__snapshots__/estimator/step-income.spec.ts/Navigating-to-en-income-renders-the-english-income-page-1.txt, frontend/e2e/__snapshots__/estimator/step-income.spec.ts/Navigating-to-fr-revenus-renders-the-french-income-page-1.txt, frontend/e2e/__snapshots__/estimator/step-marital-status.spec.ts/Navigating-to-en-marital-status-renders-the-english-marital-status-page-1.txt
adds missing form instruction to income step
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> adds form instructions to income step

frontend/app/.server/locales/common-en.json, frontend/app/.server/locales/common-fr.json, frontend/app/.server/locales/estimator-en.json, frontend/app/routes/estimator/step-income.tsx, frontend/app/routes/estimator/step-marital-status.tsx, frontend/e2e/__snapshots__/estimator/step-income.spec.ts/Navigating-to-en-income-renders-the-english-income-page-1.txt, frontend/e2e/__snapshots__/estimator/step-income.spec.ts/Navigating-to-fr-revenus-renders-the-french-income-page-1.txt, frontend/e2e/__snapshots__/estimator/step-marital-status.spec.ts/Navigating-to-en-marital-status-renders-the-english-marital-status-page-1.txt, frontend/e2e/__snapshots__/estimator/step-marital-status.spec.ts/Navigating-to-fr-etat-civil-renders-the-french-marital-status-page-1.txt, frontend/e2e/__snapshots__/index.spec.ts/Navigating-to-en-renders-the-english-dashboard-page-1.txt
fixes text in form instructions and fixes a typo
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> updates form instruction text, fixes typo

gitops/overlays/staging/patches/deployments.yaml
SNAPSHOT-00146-cdafdba8 to staging
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> deploy SNAPSHOT-00146-cdafdba8 staging

frontend/app/routes/estimator/step-income.tsx, frontend/e2e/__snapshots__/estimator/step-income.spec.ts/Navigating-to-en-income-renders-the-english-income-page-1.txt, frontend/e2e/__snapshots__/estimator/step-income.spec.ts/Navigating-to-fr-revenus-renders-the-french-income-page-1.txt
remove default values for UCCB/RDSP related fields in the income step
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> remove default values for UCCB/RDSP fields

gitops/overlays/staging/patches/deployments.yaml
deploy SNAPSHOT-00148-77507a35 to staging
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> deploy SNAPSHOT-00148-77507a35 to staging

frontend/app/.server/locales/estimator-en.json, frontend/app/.server/locales/estimator-fr.json, frontend/e2e/__snapshots__/estimator/results.spec.ts/Navigating-to-en-results-renders-the-english-results-page-1.txt, frontend/e2e/__snapshots__/estimator/results.spec.ts/Navigating-to-fr-resultats-renders-the-french-results-page-1.txt
Results text tweak
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> update result text

gitops/overlays/staging/patches/deployments.yaml
deploy latest codebase to staging
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> deploy latest codebase to staging

gitops/overlays/staging/patches/deployments.yaml
deploy latest changes to staging
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> deploy latest to staging

frontend/app/.server/locales/estimator-en.json, frontend/app/routes/estimator/results.tsx, frontend/e2e/__snapshots__/estimator/results.spec.ts/Navigating-to-en-results-renders-the-english-results-page-1.txt, frontend/e2e/__snapshots__/estimator/results.spec.ts/Navigating-to-fr-resultats-renders-the-french-results-page-1.txt
- Update partner total label in data summary.
- Update data summary placement on mobile.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> Data summary updates

gitops/overlays/staging/patches/deployments.yaml
push latest build to staging
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> push latest build to staging

gitops/overlays/staging/patches/deployments.yaml
gitops, update staging to SNAPSHOT-00158-b7809fe7
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> deploy SNAPSHOT-00158-b7809fe7 to staging

gitops/overlays/dev/hpas.yaml, gitops/overlays/dev/kustomization.yaml, gitops/overlays/shared/patches/stateful-sets.yaml, gitops/overlays/staging/configs/cdb-estimator-frontend/config.conf
Add basic HPA configuration to dev.
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
Provide screenshots or screen-recordings to help …
=> (gitops) Add basic HPA configuration to dev

frontend/react-router.config.ts
Set route discovery initial
https://reactrouter.com/start/changelog#routediscovery-config-option
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> (frontend) Set route discovery initial

frontend/package-lock.json, frontend/package.json
- chore(deps) Update dev patch
- chore(deps) Update major dev vite-plugin-static-copy
[Update dev patch](https://github.com/DTS-STN/cdb-estimator/commit/e8a9f02b04c8c9d7bab2464daa149b091922ff71)
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include …
=> Dependency updates.

gitops/overlays/staging/patches/deployments.yaml
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> Bump staging 2025-05-13

frontend/app/.server/environment/estimator.ts, frontend/e2e/__snapshots__/estimator/results.spec.ts/Navigating-to-en-results-renders-the-english-results-page-1.txt, frontend/e2e/__snapshots__/estimator/results.spec.ts/Navigating-to-fr-resultats-renders-the-french-results-page-1.txt
Update apply urls
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> Update apply urls

cdb-estimator.code-workspace, performance-tests/scripts/browser-flow.ts
- Change order of screenshot step
- Update workspace file
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> Minor cleanup

frontend/app/root.tsx, frontend/app/routes/layout.tsx, frontend/eslint.config.mjs, frontend/package-lock.json, frontend/package.json, frontend/scripts/checks-runner.ts
Install [eslint unicorn plugin](https://github.com/sindresorhus/eslint-plugin-unicorn) dependency
Install and configure [eslint-formatter-summary](https://github.com/mhipszki/eslint-formatter-summary) plugin dependency
Configure eslint unicorn plugin dependency with recommended rules. Failing rules are disabled until they are fixed in future pull requests.
<details>
``` shell
```
</details>
<details> …
=> eslint unicorn

frontend/app/.server/express/session.ts, frontend/app/.server/redis.ts, frontend/app/utils/string-utils.ts, frontend/e2e/models/PlaywrightEstimatorPage.ts, frontend/eslint.config.mjs, frontend/tests/errors/app-error.test.ts, frontend/tests/utils/currency-utils.test.ts
Fix eslint unicorn rules:
[consistent-function-scoping](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v59.0.1/docs/rules/consistent-function-scoping.md)
[error-message](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v59.0.1/docs/rules/error-message.md)
[escape-case](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v59.0.1/docs/rules/escape-case.md)
[new-for-builtins](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v59.0.1/docs/rules/new-for-builtins.md)
*(check all that apply by placing an `x` in the relevant …
=> build(frontend) Fix unicorn rules

frontend/eslint.config.mjs
Refactor Eslint config based on recent changes.
More info: https://eslint.org/blog/2025/03/flat-config-extends-define-config-global-ignores/
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your reasoning and provide any necessary context here. Feel free to include …
=> refactor(frontend) eslint configuration

frontend/app/.server/express/session.ts, frontend/app/components/session-timeout.tsx, frontend/app/routes/api/health.ts, frontend/app/utils/cdb-calculator.ts, frontend/app/utils/date-utils.ts, frontend/e2e/meta.spec.ts, frontend/eslint.config.mjs, frontend/playwright.config.ts, frontend/tests/.server/redis.test.ts, frontend/tests/components/session-timeout.test.tsx, frontend/tests/utils/cdb-calculator.test.ts
Fix the following unicorn [rules](https://github.com/sindresorhus/eslint-plugin-unicorn?tab=readme-ov-file#rules):
- unicorn/no-array-for-each
- unicorn/numeric-separators-style
- unicorn/prefer-number-properties
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
If this PR introduces significant changes, explain your …
=> fix(frontend): Eslint unicorn plugin rules

frontend/e2e/__supports/string-utils.ts, frontend/eslint.config.mjs, frontend/scripts/checks-runner.ts
unicorn lint rule prefer-type-error
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
Provide screenshots or screen-recordings to help …
=> unicorn lint rule prefer-type-error

frontend/app/.server/logging.ts, frontend/app/components/currency-field.tsx, frontend/app/components/error-summary.tsx, frontend/app/components/footer.tsx, frontend/app/utils/i18n-utils.ts, frontend/app/utils/state-utils.ts, frontend/e2e/estimator/step-income.spec.ts, frontend/eslint.config.mjs
- unicorn/no-negated-condition
- unicorn/import-style
- unicorn/prefer-spread
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> fix(frontend) eslint

frontend/app/components/error-summary.tsx, frontend/app/components/links.tsx, frontend/app/routes/layout.tsx, frontend/eslint.config.mjs, frontend/prettier.config.mjs, frontend/scripts/checks-runner.ts, frontend/tests/components/currency-field.test.tsx
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> fix(frontend) eslint unicorn issues

gitops/overlays/staging/patches/deployments.yaml
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> gitops: Update staging

frontend/app/routes/index.tsx
remove redundancy in index title
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> remove redundancy in index title

frontend/app/components/currency-field.tsx, frontend/e2e/__snapshots__/estimator/step-income.spec.ts/Navigating-to-en-income-renders-the-english-income-page-married-and-passes-a11y-checks-1.txt, frontend/e2e/__snapshots__/estimator/step-income.spec.ts/Navigating-to-en-income-renders-the-english-income-page-single-and-passes-a11y-checks-1.txt, frontend/e2e/__snapshots__/estimator/step-income.spec.ts/Navigating-to-fr-revenus-renders-the-french-income-page-married-and-passes-a11y-checks-1.txt, frontend/e2e/__snapshots__/estimator/step-income.spec.ts/Navigating-to-fr-revenus-renders-the-french-income-page-single-and-passes-a11y-checks-1.txt, frontend/e2e/__snapshots__/estimator/step-income.spec.ts/iPhone-Safari---numeric-input-test-en-single-1.txt
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> fix currency field currency symbol accessibility

frontend/app/.server/locales/estimator-en.json, frontend/app/.server/locales/estimator-fr.json, frontend/e2e/__snapshots__/index.spec.ts/Navigating-to-en-renders-the-english-dashboard-page-1.txt, frontend/e2e/__snapshots__/index.spec.ts/Navigating-to-fr-renders-the-french-dashboard-page-1.txt
describe cdb hyperlink index page's result disclaimer
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details>
=> describe cdb hyperlink index page's result disclaimer

frontend/app/components/error-summary.tsx, frontend/app/hooks/use-push-validation-error-event.ts, frontend/tests/components/error-summary.test.tsx
adds form validation error push to AA
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> adds AA validation error tracking to error summary

frontend/app/.server/environment/estimator.ts, frontend/app/routes/estimator/results.tsx, frontend/app/routes/index.tsx, frontend/e2e/estimator/results.spec.ts, frontend/e2e/index.spec.ts
adds 2 feature flags to show/hide apply and contact urls
<details>
``` shell
```
</details>
<details>
``` shell
npm run test
```
</details> …
=> add feature flag for hiding apply and contact urls

gitops/prod/base/cdb-estimator-frontend/configs/config.conf, gitops/prod/base/cdb-estimator-frontend/configs/secrets.conf, gitops/prod/base/cdb-estimator-frontend/deployments.yaml, gitops/prod/base/cdb-estimator-frontend/kustomization.yaml, gitops/prod/base/cdb-estimator-frontend/services.yaml, gitops/prod/base/redis/configs/examples/redis.conf, gitops/prod/base/redis/configs/examples/sentinel.conf, gitops/prod/base/redis/configs/init.sh, gitops/prod/base/redis/configs/primary.conf, gitops/prod/base/redis/configs/replica.conf, gitops/prod/base/redis/configs/secrets.conf, gitops/prod/base/redis/configs/sentinel.conf, gitops/prod/base/redis/kustomization.yaml, gitops/prod/base/redis/services.yaml, gitops/prod/base/redis/stateful-sets.yaml, gitops/prod/base/reloader/deployments.yaml, gitops/prod/base/reloader/kustomization.yaml, gitops/prod/base/reloader/roles.yaml, gitops/prod/base/reloader/service-accounts.yaml, gitops/prod/kustomization.yaml, gitops/prod/overlay/configs/frontend/config.conf, gitops/prod/overlay/configs/redis/replica.conf, gitops/prod/overlay/configs/redis/sentinel.conf, gitops/prod/overlay/external-secrets-frontend.yaml, gitops/prod/overlay/external-secrets-redis.yaml, gitops/prod/overlay/hpas.yaml, gitops/prod/overlay/ingresses.yaml, gitops/prod/overlay/kustomization.yaml, gitops/prod/overlay/patches/deployments-frontend.yaml, gitops/prod/overlay/patches/stateful-sets-redis.yaml
=> Setup production gitops

gitops/prod/overlay/patches/deployments-frontend.yaml
Update production gitops deployment with tmp image
=> Update production gitops deployment with tmp image

gitops/prod/overlay/configs/frontend/config.conf
Update production Adobe Analytics src to RUN
=> Update production Adobe Analytics src to RUN

gitops/prod/overlay/configs/frontend/config.conf
Reverts DTS-STN/cdb-estimator#383
=> Revert "Revert "enables apply url on prod""

gitops/prod/base/maintenance/configs/503.html, gitops/prod/base/maintenance/configs/config.conf, gitops/prod/base/maintenance/deployments.yaml, gitops/prod/base/maintenance/kustomization.yaml, gitops/prod/base/maintenance/services.yaml, gitops/prod/overlay/ingresses-maintenance.yaml, gitops/prod/overlay/kustomization.yaml, gitops/prod/overlay/patches/deployments-frontend.yaml, gitops/prod/overlay/patches/deployments-maintenance.yaml
Add 503 maintenance page to deployments
```
.\gitops\prod\overlay\kustomization.yaml
#
#
```
=> Add 503 maintenance page to deployments

gitops/prod/overlay/kustomization.yaml
Reenable live ingress once we have to go ahead
=> Reenable live ingress
